apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mule-stub
  labels:
    app: mule-stub
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mule-stub
    spec:
      containers:
      - name: mule-stub
        image: coc.icp:8500/sprint-poc/mule-stub
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mule-stub
  labels:
    app: mule-stub
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: mule-stub
  selector:
    app: mule-stub
